### ISSUE TITLE
Refactors: Needs more unit and integration tests

### ISSUE THREAD

**Issue by eser** [eser/golang-service-template#7]
We require more test coverage, particularly focusing on key components such as fx modules, middleware, HTTP router and the logging system.

NOTE: Anyone who is interested in contributing, feel free to reach out on our [Discord](https://discord.com/invite/ckS4huSvEk) for guidance and further details.

**Comment by 9ssi7** [comment]
Hi, I think I can support this project in this issue

**Comment by eser** [comment]
would be great! just don't hesitate to reach out if you need any assistance.
